### ISSUE TITLE
Can't run from Windows, python 2.7.10

### ISSUE THREAD

**Issue by MOImaker** [jdber1/opendrop#14]
Hi, 

I am unable to run opendrop. I have installed python 2.7.10, and running from the opendrop 1.1 directory.

I get the following error:

```
C:\Users\span577\Documents\opendrop-1.1\opendrop-1.1>python opendrop.py
Traceback (most recent call last):
  File "opendrop.py", line 16, in <module>
    from modules.classes import ExperimentalSetup, ExperimentalDrop, DropData, Tolerances
  File "C:\Users\span577\Documents\opendrop-1.1\opendrop-1.1\modules\classes.py", line 3, in <module>
    from de_YoungLaplace import ylderiv
  File "C:\Users\span577\Documents\opendrop-1.1\opendrop-1.1\modules\de_YoungLaplace.py", line 5, in <module>
    from numpy import sin, cos
ImportError: No module named numpy
```

**Comment by askoufis** [comment]
You need to follow all the instructions in [this](https://github.com/jdber1/opendrop#preparing-windows-10-for-opendrop) section of the README if you're trying to run opendrop on windows. If you've done that and it's still not working, try installing numpy manually via `pip` with the command `pip install numpy --user`.

**Comment by askoufis** [comment]
Closing due to inactivity.
