### ISSUE TITLE
ValueError: need more than 2 values to unpack

### ISSUE THREAD

**Issue by mw00847** [jdber1/opendrop#18]
Dear reader, 

have resolved indices problem in #11 but now recieve the below message after selecting the drop and needle.

Is this a problem with my installation or a bug?

Processing frame 1 of 1...
Traceback (most recent call last):
  File "opendrop.py", line 148, in <module>
    main()
  File "opendrop.py", line 85, in main
    extract_drop_profile(raw_experiment, user_inputs)
  File "/home/mat/opendrop/opendrop-1.1/modules/extract_profile.py", line 16, in extract_drop_profile
    profile, raw_experiment.ret = detect_edges(profile_crop, raw_experiment, user_inputs.drop_region, -1, 1)
  File "/home/mat/opendrop/opendrop-1.1/modules/extract_profile.py", line 56, in detect_edges
    _,contours, hierarchy = cv2.findContours(edges,cv2.RETR_TREE,cv2.CHAIN_APPROX_NONE)
ValueError: need more than 2 values to unpack

**Comment by mw00847** [comment]
found this to be a problem with the version of opencv running,

https://stackoverflow.com/questions/20851365/opencv-contours-need-more-than-2-values-to-unpack
