### ISSUE TITLE
Error when exporting results if needle area is not specified (pixel scale).

### ISSUE THREAD

**Issue by Kaiman777** [jdber1/opendrop#55]
Hello. An error has been noticed: if the user does not specify the needle area, only the pixel scale, then the analysis passes, but the export does not work. The results only contain an empty param.ini (picture 1). But if you specify the area, the export works (picture 2). During an unsuccessful export, an error occurs (picture 3). Perhaps it is worth either inserting a warning on the screen, or not allowing the user to enter the pixel and needle scale parameters until the needle area is specified. 
The error text:
Traceback (most recent call last):
  File "../opendrop/app/ift/analysis_saver/component.py", line 178, in <lambda>
  File "../opendrop/app/ift/analysis_saver/component.py", line 323, in ok
  File "../opendrop/app/ift/ift_experiment.py", line 152, in hdl_ok
  File "../opendrop/app/ift/services/session.py", line 141, in save_analyses
  File "../opendrop/app/ift/analysis_saver/save_functions.py", line 58, in save_drops
  File "../opendrop/app/ift/analysis_saver/save_functions.py", line 107, in _save_individual
  File "../opendrop/app/ift/analysis_saver/save_functions.py", line 155, in _save_drop_params
AttributeError: 'NoneType' object has no attribute 'x0'

------------------

![1_no_needle_region_only_px](https://github.com/user-attachments/assets/2a9a6637-b7dc-4d0f-ac1a-63ff5dee05bd)
![2_needle_and_scale](https://github.com/user-attachments/assets/66488da9-b215-42b0-8a59-7be7ac66ca1b)
![3_save_error_pic](https://github.com/user-attachments/assets/8dd2ac3f-1bc5-48bf-ad05-d311ec8304e9)

**Comment by eugenhu** [comment]
Thanks for the bug report. The error message looks clear. For now, you can just always select a needle region and a pixel scale. If a pixel scale is specified, the needle width is ignored for the scale calculation. If this works for you, then I don't plan on fixing this bug any time soon, apologies.
